### ISSUE TITLE
Steering Committee minutes

### ISSUE THREAD

**Issue by seabass-labrax** [spdx/meetings#102]
As per [our new governance](https://github.com/spdx/governance/blob/main/5._Governance.md), the SPDX Steering Committee will publish meeting minutes as a summary of topics discussed during its meetings. Will these be uploaded to this repository, or should I be watching another repository/website? Thanks! :)

**Comment by seabass-labrax** [comment]
Ping @swinslow; would you be able to take a look at this please? Thank you :)

**Comment by swinslow** [comment]
Hi @seabass-labrax -- thanks for the reminder on this, and also the @ mention  :)  

Yes, we'll begin posting the meeting minutes in summary form into this meetings repo. I'm expecting (hoping) to get that going in the next couple of days.

**Comment by seabass-labrax** [comment]
Thank you; its great to hear that :)
