### ISSUE TITLE
Request to add INSTALL to PackagePurpose set of enumerated values

### ISSUE THREAD

**Issue by rjb4standards** [spdx/meetings#142]
Please consider adding "INSTALL" as a member of the PackagePurpose set of options.

**Comment by swinslow** [comment]
Hi @rjb4standards, was this issue meant to be filed in the spdx-spec repo instead of this meetings minutes repo?

**Comment by rjb4standards** [comment]
Steve, this has been resolved within the V 2.3 initiative.
