### ISSUE TITLE
Delete duplicate copies of general meeting minutes

### ISSUE THREAD

**Issue by swinslow** [spdx/meetings#333]
Whoops... #332 set up subfolders by year under general/ for the general team meeting minutes, but it looks like it copied the files rather than moving them. So the originals are still directly under general/ as well  :)

@rnjudge I won't have a chance to revise this right now -- feel free to send a PR if you want, or I'll revise once I'm back at a computer and available later!

**Comment by rnjudge** [comment]
@swinslow huh, I definitely `mv`ed the files to the new directories when I was making the changes.. perhaps something funky with git? Let me take a look and open a PR.
