### ISSUE TITLE
Request for team labels in GitHub

### ISSUE THREAD

**Issue by bact** [spdx/meetings#593]
As there are growing numbers of issues and PRs, having labels will help contributors organise and audience find relevant info easier.

When open PR for a meeting minute, the contributor may assign a label (if they have a permission), so it can be easily tracked.

Purposed GitHub labels, taken from existing team and topical group names:

- `AI`* or `AI and Data`
- `Asia`* or `Asia Tech`
- `Build`*
- `Canonical`* or `Canonicalisation`
- `General`*
- `Implementers`*
- `Joint`*
- `Legal`*
- `Outreach`*
- `Safety`* (Functional Safety / FuSa)
- `Security`*
- `Serialisation`*
- `Service`* (Software as a Service)
- `Hardware`
- `Steering`*
- `Tech`*

(*currently used as a folder name for the corresponding meeting minutes)

**Comment by goneall** [comment]
@robcraig-LF - If I create the labels, could you add them to the PR's when posting the minutes?

I'll probably use the shorter name.

**Comment by robcraig-LF** [comment]
It doesn't appear as if I have the required permission level to assign labels...sorry.

**Comment by goneall** [comment]
@robcraig-LF I created all the label with the exception of "joint".

Since "joint" is a joint call with tech and legal, I suggest we add both of those labels rather than having a "joint" label.

If you could go through the backlog of open pull requests and add the labels, that would be very helpful.

**Comment by bact** [comment]
> If you could go through the backlog of open pull requests and add the labels, that would be very helpful.

You can use this #592 to assist that.

**Comment by bact** [comment]
I think we can close this issue.
